name: 'olist'
version: '1.0.0'

profile: 'olist'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_utils']

target-path: "target"      
clean-targets:        
  - "target"
  - "dbt_packages"

seeds:
  olist:
    sales:
      +schema: sales_raw
    marketing:
      +schema: marketing_raw

models:
  olist:
    staging:
      sales:
        +materialized: view
        +schema: stg
      marketing:
        +materialized: view
        +schema: mkt_stg
    marts:
      sales:
        +materialized: table
        +schema: marts
      marketing:
        +materialized: table
        +schema: mkt_marts
    snapshot:
      +schema: snapshot
    intermediate:
      +materialized: view
      +schema: intermediate
